#!/bin/bash
# Quick script to fill GitHub contribution graph for Manisha
set -euo pipefail

cd "/Users/satyamrastogi/manisha-cyber-intel"

echo "🚀 Quick-filling GitHub contribution graph..."

# Simple date function that works on macOS
add_days() {
  local base_date="$1"
  local days="$2"
  if command -v gdate >/dev/null; then
    gdate -d "$base_date + $days days" +%Y-%m-%d
  else
    python3 -c "
import datetime
base = datetime.datetime.strptime('$base_date', '%Y-%m-%d')
result = base + datetime.timedelta(days=$days)
print(result.strftime('%Y-%m-%d'))
"
  fi
}

# Create many commits across the year
start_date="2025-01-01"
end_date="2026-05-09"

# Generate random contributions
for i in {1..365}; do
  commit_date=$(add_days "$start_date" "$i")

  # Skip some days randomly for realistic pattern
  if (( RANDOM % 100 < 25 )); then
    continue  # 25% chance to skip
  fi

  # Random hour between 9-18
  hour=$((9 + RANDOM % 10))
  minute=$((RANDOM % 60))
  commit_time="${commit_date} ${hour}:$(printf "%02d" $minute):00"

  # Random content types
  case $((RANDOM % 4)) in
    0)
      mkdir -p daily
      echo "# Daily Intel Brief - $commit_date

**Analyst**: Manisha Dua, DevSecOps Engineer
**Priority**: High

## Cybersecurity Updates
- Critical vulnerability analysis completed
- Threat intelligence feeds updated
- DevSecOps pipeline security enhanced
- Container scanning baseline updated

---
*Generated by Manisha Dua, DevSecOps Engineer*" > "daily/brief-$commit_date.md"
      ;;

    1)
      mkdir -p analysis
      echo "# Threat Analysis - $commit_date

**Analyst**: Manisha Dua, DevSecOps Engineer

## Analysis Summary
Advanced persistent threat campaign targeting cloud infrastructure.
DevSecOps controls updated to address emerging TTPs.

## Recommendations
- Enhanced monitoring deployed
- CI/CD security gates updated
- Container runtime protection activated

---
*Analysis by Manisha Dua, DevSecOps Engineer at BAMKO*" > "analysis/analysis-$commit_date.md"
      ;;

    2)
      mkdir -p configs
      echo "# DevSecOps Config - $commit_date
# Author: Manisha Dua, DevSecOps Engineer

security:
  baseline_version: \"2.$(( RANDOM % 10 ))\"
  threat_detection: enabled
  container_scanning: active
  pipeline_hardening: enforced
  compliance_monitoring: continuous

automation:
  incident_response: automated
  threat_intelligence: updated
  security_reporting: enabled" > "configs/security-$commit_date.yml"
      ;;

    *)
      mkdir -p updates
      echo "# Security Update - $commit_date

**Engineer**: Manisha Dua, DevSecOps
**Update Type**: Security Enhancement

## Changes
- Threat detection rules updated
- Security baseline enhanced
- DevSecOps automation improved
- Compliance monitoring activated

---
*Security engineering by Manisha Dua*" > "updates/update-$commit_date.md"
      ;;
  esac

  # Commit with proper date
  git add .
  git commit --date="$commit_time" -m "security: daily intelligence and DevSecOps updates for $commit_date

Enhanced threat detection and security automation.
Container security and CI/CD pipeline hardening deployed.

DevSecOps engineering by Manisha Dua" >/dev/null

  # Show progress every 25 commits
  if (( i % 25 == 0 )); then
    echo "✅ Generated $i commits (current date: $commit_date)"
  fi
done

echo "🔄 Pushing all contributions to GitHub..."
git push origin main --force-with-lease

echo "✅ Quick contribution fill completed!"
echo "🎉 Repository: https://github.com/Manishadua/cyber-daily-intel"
echo "📊 Generated ~275+ commits across 13+ months"
echo "🟢 GitHub contribution graph should now be consistently green!"